# steps  imges to df by idetifying the relation
- read 
- resize
- flatten
- merge


In [11]:
import os 
import cv2
import numpy as np 
import pandas as  pd

In [13]:
 os.mkdir(r"C:\Users\krish\Documents\flowerSpecies")

In [21]:
 os.mkdir(r"C:\Users\krish\Documents\flowerSpecies\ROSE_WHITE")

In [17]:
 os.mkdir(r"C:\Users\krish\Documents\flowerSpecies\SUNFLOWER")

In [19]:
 os.mkdir(r"C:\Users\krish\Documents\flowerSpecies\LiLy")

In [23]:
 os.mkdir(r"C:\Users\krish\Documents\flowerSpecies\ROSE_PINK")

In [40]:
l = os.listdir(r"C:\Users\krish\Documents\flowerSpecies") 
l # spices

['LiLy', 'ROSE_PINK', 'ROSE_WHITE', 'SUNFLOWER']

In [72]:
features = [] 
class_labels = []
for y in l:  #['LiLy', 'ROSE_PINK', 'ROSE_WHITE', 'SUNFLOWER']
    for x in os.listdir(r"C:\Users\krish\Documents\flowerSpecies\{}".format(y)) : 
        img=cv2.imread(r"C:\Users\krish\Documents\flowerSpecies\{}\{}".format(y,x),0)  # read in gray scale
        img = cv2.resize(img,(60,60)) 
        img = img.flatten()  
        features.append(img) 
        class_labels.append(y)
        
    

In [73]:
features      

[array([66, 68, 66, ..., 59, 55, 54], dtype=uint8),
 array([72, 72, 71, ..., 33, 32, 31], dtype=uint8),
 array([73, 66, 63, ..., 53, 54, 50], dtype=uint8),
 array([174, 189, 183, ...,  50,  19,  18], dtype=uint8)]

In [74]:
class_labels

['LiLy', 'ROSE_PINK', 'ROSE_WHITE', 'SUNFLOWER']

In [75]:
df = pd.DataFrame(features)

In [80]:
df["label"] = class_labels

In [82]:
df

0    1    2    3    4    5    6    7    8    9  ...  3591  3592  3593  \
0   66   68   66   68   68   68   73   75   83   88  ...    76    73    70   
1   72   72   71   65   69   73   75   70   69   63  ...    54    57    56   
2   73   66   63   84   90   80   77   78   80   88  ...    67    61    60   
3  174  189  183  140  136  182  192  175  135  167  ...    40    43    45   

   3594  3595  3596  3597  3598  3599       label  
0    66    64    59    59    55    54        LiLy  
1    47    43    35    33    32    31   ROSE_PINK  
2    53    54    51    53    54    50  ROSE_WHITE  
3    49    56    52    50    19    18   SUNFLOWER  

[4 rows x 3601 columns]

In [86]:
features = [] 
class_labels = []
for y in l:  #['LiLy', 'ROSE_PINK', 'ROSE_WHITE', 'SUNFLOWER']
    for x in os.listdir(r"C:\Users\krish\Documents\flowerSpecies\{}".format(y)) : 
        img=cv2.imread(r"C:\Users\krish\Documents\flowerSpecies\{}\{}".format(y,x),1)  # read in gray scale
        img = cv2.resize(img,(60,60)) 
        img = img.flatten()  
        features.append(img) 
        class_labels.append(y)
        
    

In [88]:
df = pd.DataFrame(features)

In [90]:
df["label"] = class_labels

In [92]:
df

0    1    2    3    4    5    6    7    8    9  ...  10791  10792  10793  \
0  114   70   41  116   72   43  110   70   41  116  ...    100     63     37   
1   54   63   97   54   62   99   57   59   99   51  ...     28     33     36   
2   66   74   74   61   66   67   58   65   62   79  ...     48     55     52   
3  188  176  164  200  191  182  197  185  173  151  ...     31     47     64   

   10794  10795  10796  10797  10798  10799       label  
0     95     58     34     93     57     33        LiLy  
1     28     31     35     29     30     34   ROSE_PINK  
2     49     55     54     45     52     49  ROSE_WHITE  
3     15     20     19     14     19     18   SUNFLOWER  

[4 rows x 10801 columns]

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Columns: 10801 entries, 0 to label
dtypes: object(1), uint8(10800)
memory usage: 42.3+ KB
