# VIDEO TO dataframe

In [1]:
import cv2 
import numpy as np 
import pandas as pd

In [3]:
import os 

In [22]:
os.mkdir(r"C:\Users\krish\Documents\identify_hut_Palace\hut")

In [24]:
os.mkdir(r"C:\Users\krish\Documents\identify_hut_Palace\palace")

In [5]:
frames = cv2.VideoCapture(r"C:\Users\krish\Documents\identify_hut_Palace\hut.mp4")  # converting any videos to frames 
while True: 
    suc,img = frames.read()  # if the frames present than return the booleam true or else False
    if suc == False: 
        break
    
    cv2.imshow("vid",img) 
    if cv2.waitKey(1) & 255 == ord("C"): # comes out ffrom the window at any  time after we give the input  
        break
cv2.destroyAllWindows()
    


In [9]:
frames = cv2.VideoCapture(r"C:\Users\krish\Documents\identify_hut_Palace\hut.mp4")  # converting any videos to frames 
while True: 
    suc,img = frames.read()  # if the frames present than return the booleam true or else False
    if suc == False: 
        break
    b,g,r = cv2.split(img) 
    z = np.zeros(b.shape,dtype = np.uint8) 
    cv2.imshow("blue",cv2.merge([b,z,z])) 
    cv2.imshow("green",cv2.merge([z,g,z])) 
    cv2.imshow("RED",cv2.merge([z,z,r]))
    cv2.imshow("vid",img) 
    if cv2.waitKey(1) & 255 == ord("C"): # comes out ffrom the window at any  time after we give the input  
        break 
cv2.destroyAllWindows()
    

# 

In [53]:
l = os.listdir(r"C:\Users\krish\Documents\identify_hut_Palace") 
l

['hut', 'hut.mp4', 'palace', 'palace.mp4']

In [7]:
features = []
frames = cv2.VideoCapture(r"C:\Users\krish\Documents\identify_hut_Palace\hut.mp4")  # converting any videos to frames 
while True: 
    suc,img = frames.read()  # if the frames present than return the booleam true or else False
    if suc == False: 
        break  
    #print(img.shape)
    
    cv2.imshow("vid",img)  
    img = cv2.resize( img,img.shape[:-1])    
    img = img.flatten()
    features.append(img) 


    if cv2.waitKey(1) & 255 == ord("C"): # comes out ffrom the window at any  time after we give the input  
        break
cv2.destroyAllWindows()
    

In [9]:
features

[array([35, 23, 16, ...,  7,  7,  7], dtype=uint8),
 array([48, 36, 29, ...,  8,  8,  8], dtype=uint8),
 array([35, 23, 16, ...,  8,  8,  8], dtype=uint8),
 array([35, 23, 16, ...,  8,  8,  8], dtype=uint8),
 array([34, 22, 15, ...,  8,  8,  8], dtype=uint8),
 array([37, 25, 18, ..., 14, 14, 14], dtype=uint8),
 array([35, 23, 16, ..., 10, 10, 10], dtype=uint8),
 array([28, 16,  9, ..., 11, 11, 11], dtype=uint8),
 array([45, 33, 26, ..., 11, 11, 11], dtype=uint8),
 array([36, 24, 17, ..., 13, 13, 13], dtype=uint8),
 array([35, 23, 16, ..., 11, 11, 11], dtype=uint8),
 array([33, 21, 14, ..., 11, 11, 11], dtype=uint8),
 array([29, 17, 10, ..., 11, 11, 11], dtype=uint8),
 array([46, 34, 27, ..., 11, 11, 11], dtype=uint8),
 array([34, 22, 15, ..., 11, 11, 11], dtype=uint8),
 array([38, 27, 20, ..., 11, 11, 11], dtype=uint8),
 array([37, 25, 18, ..., 10, 10, 10], dtype=uint8),
 array([39, 27, 20, ..., 11,  8,  9], dtype=uint8),
 array([46, 34, 27, ..., 11, 11, 11], dtype=uint8),
 array([37, 

In [11]:
features[:100]

[array([35, 23, 16, ...,  7,  7,  7], dtype=uint8),
 array([48, 36, 29, ...,  8,  8,  8], dtype=uint8),
 array([35, 23, 16, ...,  8,  8,  8], dtype=uint8),
 array([35, 23, 16, ...,  8,  8,  8], dtype=uint8),
 array([34, 22, 15, ...,  8,  8,  8], dtype=uint8),
 array([37, 25, 18, ..., 14, 14, 14], dtype=uint8),
 array([35, 23, 16, ..., 10, 10, 10], dtype=uint8),
 array([28, 16,  9, ..., 11, 11, 11], dtype=uint8),
 array([45, 33, 26, ..., 11, 11, 11], dtype=uint8),
 array([36, 24, 17, ..., 13, 13, 13], dtype=uint8),
 array([35, 23, 16, ..., 11, 11, 11], dtype=uint8),
 array([33, 21, 14, ..., 11, 11, 11], dtype=uint8),
 array([29, 17, 10, ..., 11, 11, 11], dtype=uint8),
 array([46, 34, 27, ..., 11, 11, 11], dtype=uint8),
 array([34, 22, 15, ..., 11, 11, 11], dtype=uint8),
 array([38, 27, 20, ..., 11, 11, 11], dtype=uint8),
 array([37, 25, 18, ..., 10, 10, 10], dtype=uint8),
 array([39, 27, 20, ..., 11,  8,  9], dtype=uint8),
 array([46, 34, 27, ..., 11, 11, 11], dtype=uint8),
 array([37, 

In [ ]:
dfpd.DataFrame(features[:100])

In [55]:
folders = [] 
videos = []
for i in l:  
    if i.endswith(".mp4"): 
        videos.append(i) 
    else: 
        folders.append(i)
    

In [57]:
folders

['hut', 'palace']

In [31]:
for  vid in videos: # ['hut.mp4', 'palace.mp4'] 
     frames = cv2.VideoCapture(r"C:\Users\krish\Documents\identify_hut_Palace\{}".format(vid))   
   for img in frames:
       c=1
       cv2.imwrite(r"C:\Users\krish\Documents\identify_hut_Palace\{}\{}{}.jpg".format(vid.split(".")[0],vid.split(".")[0],c)img) 
       c+=1
          

IndentationError: unindent does not match any outer indentation level (<string>, line 3)

In [47]:
for  vid in videos: # ['hut.mp4', 'palace.mp4'] 
    c = 1
    frames = cv2.VideoCapture(r"C:\Users\krish\Documents\identify_hut_Palace\{}".format(vid))  
    while True:
        succ,img = frames.read() 
        if succ == False :
            break 
        cv2.imwrite(r"C:\Users\krish\Documents\identify_hut_Palace\{}\{}{}.jpg".format(vid.split(".")[0],vid.split(".")[0],c),img) 
        c+=1
        
    
    
             

In [59]:
x = [] 
y = []
for fol in folders:  # ['hut', 'palace']  
    for img in os.listdir(r"C:\Users\krish\Documents\identify_hut_Palace\{}".format(fol)):  
        img = cv2.imread(r"C:\Users\krish\Documents\identify_hut_Palace\{}\{}".format(fol,img)) 
        img = cv2.resize(img,img.shape[:-1]) 
        img = img.flatten()  
        x.append(img) 
        y.append(fol)
        
        
    

In [61]:
x

[array([34, 21, 15, ...,  7,  7,  7], dtype=uint8),
 array([35, 23, 17, ..., 13, 13, 13], dtype=uint8),
 array([37, 28, 19, ..., 15, 15, 15], dtype=uint8),
 array([43, 34, 25, ..., 15, 15, 15], dtype=uint8),
 array([36, 27, 18, ..., 15, 15, 15], dtype=uint8),
 array([30, 22, 13, ..., 15, 15, 15], dtype=uint8),
 array([43, 34, 25, ..., 15, 15, 15], dtype=uint8),
 array([32, 23, 14, ..., 15, 15, 15], dtype=uint8),
 array([36, 27, 18, ..., 15, 15, 15], dtype=uint8),
 array([34, 25, 16, ..., 15, 15, 15], dtype=uint8),
 array([42, 33, 24, ..., 15, 15, 15], dtype=uint8),
 array([42, 33, 24, ..., 15, 15, 15], dtype=uint8),
 array([34, 22, 16, ..., 11, 11, 11], dtype=uint8),
 array([42, 33, 24, ..., 15, 15, 15], dtype=uint8),
 array([37, 28, 19, ..., 15, 15, 15], dtype=uint8),
 array([37, 28, 19, ..., 15, 15, 15], dtype=uint8),
 array([35, 26, 16, ..., 15, 15, 15], dtype=uint8),
 array([30, 21, 12, ..., 13, 13, 13], dtype=uint8),
 array([34, 25, 16, ..., 25, 25, 25], dtype=uint8),
 array([35, 

In [63]:
dfpd.DataFrame(x)

MemoryError: 